name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            requirements-ci.txt

      - name: Install PyTorch (CPU wheels only)
        run: |
          python -m pip install --upgrade pip wheel
          pip install --index-url https://download.pytorch.org/whl/cpu \
            torch==2.8.0 torchvision==0.23.0

      - name: Install project deps
        run: |
          pip install -r requirements-ci.txt --no-python-version-warning --disable-pip-version-check

      - name: Lint & test
        run: |
          flake8 .
          pytest -q
