name: Optimized CI

on:
  push:
    branches: [main, develop]
    paths:
      - '**.py'
      - 'requirements*.txt'
      - '.github/workflows/**'
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_COMPILE: "1"
  COVERAGE_CORE: sysmon  # Python 3.12+ optimization

jobs:
  quick-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # For changed files detection
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v46
        with:
          files: '**.py'
      
      - name: Fast security scan (changed files only)
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          pip install bandit
          bandit -r ${{ steps.changed.outputs.all_changed_files }}
      
      - name: Quick lint
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          pip install ruff
          ruff check ${{ steps.changed.outputs.all_changed_files }}

  test:
    needs: quick-checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ['3.10', '3.12']
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install -e .[test]
          pip install pytest-xdist  # Parallel execution
      
      - name: Run tests (parallel)
        run: |
          pytest -n auto \
            --cov=src \
            --cov-report=xml \
            --cov-report=term-missing \
            --durations=10
      
      - name: Upload coverage
        if: matrix.python-version == '3.12'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
