# .github/workflows/pylint.yml
name: pylint

on:
  pull_request:
    paths: ["**/*.py"]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            requirements-ci.txt
            requirements.txt
            pyproject.toml

      - name: Cache Pylint cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pylint
          key: ${{ runner.os }}-pylint-${{ hashFiles('.pylintrc', 'pyproject.toml') }}-${{ matrix.python-version || '3.12' }}
          restore-keys: |
            ${{ runner.os }}-pylint-

      - name: Install dependencies (lean)
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_PROGRESS_BAR: "off"
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-ci.txt ]; then
            pip install -r requirements-ci.txt
          else
            pip install pylint
          fi

      - name: Run Pylint
        shell: bash
        run: |
          set -euo pipefail
          # Collect tracked Python files (robust to spaces/newlines)
          git ls-files -z '*.py' > pyfiles.z || true
          if [ ! -s pyfiles.z ]; then
            echo "No Python files to lint."
            exit 0
          fi
          # Lint with parallel workers; fail if score < 8.0 (tune as needed)
          xargs -0 pylint -j 0 --fail-under=8.0 < pyfiles.z