# file: .github/workflows/pylint.yml
name: pylint

on:
  pull_request:
    paths: ["**/*.py"]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements.txt
            requirements-ci.txt

      - name: Cache Pylint cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pylint
          key: ${{ runner.os }}-pylint-${{ hashFiles('.pylintrc', 'pyproject.toml') }}-3.12
          restore-keys: |
            ${{ runner.os }}-pylint-

      - name: Install dev-lean extras (ensures imports resolve) + pylint
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_PROGRESS_BAR: "off"
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev-lean]" pylint

      - name: Generate legacy shims from tests
        run: python tools/gen_legacy_shims.py

      - name: Run Pylint
        shell: bash
        run: |
          set -euo pipefail
          git ls-files -z '*.py' > pyfiles.z || true
          if [ ! -s pyfiles.z ]; then
            echo "No Python files to lint."
            exit 0
          fi
          pylint -j 0 --fail-under=8.0 $(tr '\0' ' ' < pyfiles.z)
