name: pylint

on:
  pull_request:
    paths: [ "**/*.py" ]
  push:
    branches: [ main ]  # Optional: run lint on direct pushes too

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-ci.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies (lean)
        env:
          PIP_NO_CACHE_DIR: "1"
          PIP_PROGRESS_BAR: "off"
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-ci.txt ]; then
            pip install --no-cache-dir -r requirements-ci.txt
          fi
          pip install --no-cache-dir pylint

      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py' || echo '') || true
