# file: .github/workflows/shim-sync.yml  (manual, one-click pre-generate & commit)
name: shim-sync
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-shims:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Generate shims (write)
        run: |
          python -m pip install --upgrade pip
          python tools/gen_legacy_shims.py --write
      - name: Commit shims (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(shims): add/update legacy shims from tests"
          commit_user_name: github-actions
          commit_user_email: github-actions@users.noreply.github.com
          file_pattern: "*.py"
