# .github/workflows/summary.yml
name: Summarize new issues
on:
  issues:
    types: [opened]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Generate summary with OpenAI
        id: summarize
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          python - <<'PY'
          import os, openai, textwrap
          openai.api_key = os.environ["OPENAI_API_KEY"]
          title = os.environ.get("ISSUE_TITLE", "")
          body  = os.environ.get("ISSUE_BODY", "")
          prompt = textwrap.dedent(f"""
          Summarize the following GitHub issue in one concise paragraph:
          Title: {title}
          Body:
          {body}
          """)
          response = openai.chat.completions.create(
              model="gpt-4o-mini",
              messages=[{"role": "user", "content": prompt}],
              max_tokens=120,
              temperature=0.2,
          )
          text = response.choices[0].message.content.strip()
          with open(os.environ["GITHUB_STEP_SUMMARY"], "w", encoding="utf-8") as f:
              f.write(text)
          print("summary-output=" + text)
          PY

      - name: Post summary as comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue comment $ISSUE_NUMBER \
            --body "$(cat $GITHUB_STEP_SUMMARY)"
